name: first demo 
on:
 push:
  branches: 
  - main 
jobs:
  demo_job:
   runs-on: self-hosted
   steps:
    #- uses: actions/demo-repo@main
    - name: run a one-line script
      run: sh ./first.sh
       
  
   
  
